### ISSUE TITLE
Documentation currently fails to build

### ISSUE THREAD

**Issue by dented42** [Kalimehtar/binary-class#1] opened 2014-07-09 01:30 UTC
When I try to install binary-class, the documentation building phase generates an error and no documentation ends up getting built. The output from `raco setup` is

```
raco setup: 0 running: <pkgs>/binary-class/binary-class/manual.scrbl
raco setup: error running: (lib binary-class/manual.scrbl)
raise-argument-error: contract violation
  expected: symbol?
  given: #<procedure:path->pkg>
  argument position: 1st
  other arguments...:
   "path-string?"
   '(#<path:/Users/dented42/Library/Racket/6.0/pkgs/binary-class/binary-class/main.rkt> safe)
  context...:
   /Applications/Racket/collects/pkg/path.rkt:72:0: path->pkg+subpath+collect*
   /Applications/Racket/collects/pkg/path.rkt:154:0: path->pkg30
   /Applications/Racket/share/pkgs/scribble-lib/scribble/private/manual-mod.rkt:183:0: *defmodule
   /Users/dented42/Library/Racket/6.0/pkgs/binary-class/binary-class/manual.scrbl: [running body]
   /Applications/Racket/share/pkgs/racket-index/setup/scribble.rkt:876:0: load-doc/ensure-prefix
   /Applications/Racket/share/pkgs/racket-index/setup/scribble.rkt:1117:13
   /Applications/Racket/collects/setup/parallel-do.rkt:420:20: loop
raise-argument-error: contract violation
  expected: symbol?
  given: #<procedure:path->pkg>
  argument position: 1st
  other arguments...:
   "path-string?"
   '(#<path:/Users/dented42/Library/Racket/6.0/pkgs/binary-class/binary-class/main.rkt> safe)
  context...:
   /Applications/Racket/collects/pkg/path.rkt:72:0: path->pkg+subpath+collect*
   /Applications/Racket/collects/pkg/path.rkt:154:0: path->pkg30
   /Applications/Racket/share/pkgs/scribble-lib/scribble/private/manual-mod.rkt:183:0: *defmodule
   /Users/dented42/Library/Racket/6.0/pkgs/binary-class/binary-class/manual.scrbl: [running body]
   /Applications/Racket/share/pkgs/racket-index/setup/scribble.rkt:876:0: load-doc/ensure-prefix
   /Applications/Racket/share/pkgs/racket-index/setup/scribble.rkt:1117:13
   /Applications/Racket/collects/setup/parallel-do.rkt:420:20: loop
```

**Comment by Kalimehtar** [comment] 2014-07-09 02:47
Can't reproduce.

Resolving "binary-class" via http://download.racket-lang.org/releases/6.0.1/catalog/
Resolving "binary-class" via http://pkgs.racket-lang.org
Downloading https://github.com/Kalimehtar/binary-class/tarball/2be496df48b848b76541b0ce7f1e11b8beea8e1b
raco setup: version: 6.0.1 [3m]
raco setup: installation name: 6.0.1
raco setup: variants: 3m
raco setup: main collects: C:\Program Files\Racket\collects
raco setup: collects paths: 
raco setup:   C:\Documents and Settings\Monk.SGES\Application Data\Racket\6.0.1\collects
raco setup:   C:\Program Files\Racket\collects
raco setup: main pkgs: C:\Program Files\Racket\share\pkgs
raco setup: pkgs paths: 
raco setup:   C:\Program Files\Racket\share\pkgs
raco setup:   C:\Documents and Settings\Monk.SGES\Application Data\Racket\6.0.1\pkgs
raco setup: links files: 
raco setup:   C:\Program Files\Racket\share\links.rktd
raco setup:   C:\Documents and Settings\Monk.SGES\Application Data\Racket\6.0.1\links.rktd
raco setup: main docs: C:\Program Files\Racket\doc
raco setup: --- updating info-domain tables ---
raco setup: updating: C:\Documents and Settings\Monk.SGES\Application Data\Racket\6.0.1\share\info-cache.rktd
raco setup: --- pre-installing collections ---
raco setup: --- installing foreign libraries ---
raco setup: --- installing shared files ---
raco setup: --- compiling collections ---
raco setup: --- parallel build using 2 jobs ---
raco setup: 1 making: <pkgs>/binary-class/binary-class
raco setup: 1 making: <pkgs>/binary-class/binary-class/private
raco setup: --- creating launchers ---
raco setup: --- building documentation ---
raco setup: 0 running: <pkgs>/binary-class/binary-class/manual.scrbl
raco setup: 1 rendering: <pkgs>/binary-class/binary-class/manual.scrbl
raco setup: 0 rendering: <pkgs>/racket-index/scribblings/main/user/local-redirect.scrbl
raco setup: 0 rendering: <pkgs>/racket-index/scribblings/main/user/release.scrbl
raco setup: 1 rendering: <pkgs>/racket-index/scribblings/main/user/search.scrbl
raco setup: 0 rendering: <pkgs>/racket-index/scribblings/main/user/start.scrbl
raco setup: --- installing collections ---
raco setup: --- post-installing collections ---

Installed from DrRacket. equivalent command line
raco pkg install --deps search-auto binary-class

**Closed as completed** 2020-11-29 07:45 UTC
